### ISSUE TITLE
Error in Interceptor

### ISSUE THREAD

**Issue by mhosman** [Devstackr/task-manager-mean-stack#1]
If refresh token fails with 401, it's not logging out. I think there is some error in the catchError (code is not being executed).

Code not being executed:
![Captura](https://user-images.githubusercontent.com/5334175/57560143-582be280-735b-11e9-9d3d-a8ea31e1ba07.PNG)

**Comment by Devstackr8** [comment]
@mhosman Hi, yes - this is definitely an issue.
The refreshing mechanism works when the refresh token is valid, but if the refresh token is not valid then the catchError won't be executed - good catch :)
Here is some code that will fix the issue:
```js
// ...

return next.handle(request).pipe(
      catchError((error: HttpErrorResponse) => {

        // NEW CODE:
        if (error.status === 401 && request.url.endsWith('/users/me/access-token')) {
          // then this means that the refresh token has expired
          console.log("refresh token expired");
          this.refreshingAccessToken = false;
          this.authService.logout();
          return empty();
        }
        // END NEW CODE
        // ...
```

Let me know if this works for you - and thanks for creating this issue :)

**Comment by mhosman** [comment]
Thanks @Devstackr8. What's the difference between this code with:
`accessTokenRefreshed: Subject<any> = new Subject();`
and the one in the video without it?
Thank you!

**Comment by Devstackr8** [comment]
Hi @mhosman 
We need the `accessTokenRefreshed` Subject so that we can 'retry' requests after the refreshing process has completed.
A Subject is very useful for this since it is both an observer and an emitter (can run .next() to inform subscribers of the subject that something has happened). And its also very convinient becuase HTTP interceptors rely on Observables.

This is the code where we use that Subject (for reference)
``` ts
refreshAccessToken() {
    if (this.refreshingAccessToken) {
      return new Observable(observer => {
        this.accessTokenRefreshed.subscribe(() => {
          // this code will run when the access token has been refreshed
          observer.next();
          observer.complete();
        })
      })
    } else {
      this.refreshingAccessToken = true;
      return this.authService.getNewAccessToken().pipe(
        tap(() => {
          console.log("Access Token Refreshed");
          this.refreshingAccessToken = false;
          this.accessTokenRefreshed.next();
        })
      )
    }
  }
```

So basically, if this method, `refreshAccessToken()`, gets called after we have started the refresh process (by sending the request to the API, but haven't recieved a response back yet), then we want the HTTP interceptor to wait until the access token has been refreshed before carrying on.

This can be kind of confusing... but lets go through it step by step
In the main intercept method we have this bit of code:
``` ts
if (error.status == 401) {
          // 401 error so we are unauthorized

          // Refresh the Access Token
          return this.refreshAccessToken().pipe(
            switchMap(() => {
              request = this.addAuthHeader(request);
              return next.handle(request);
            }),
            catchError((err: any) => {
              console.log("catching error");
              console.log(err);
              this.refreshingAccessToken = false;
              this.authService.logout();
              return empty();
            })
          )
        }
```
The code in the switchMap is the interesting part.
This code 'retries' the request.
This code will only run after the observable that was returned from `this.refreshAccessToken()` emits a value (which we only do once the Access Token has been refreshed).

I hope that helps - please let me know if that didn't make sense :)

**Comment by mhosman** [comment]
Great @Devstackr8, it's working as expected. 

**Just one issue:**
If the token is being refreshed and you change the route, the current request (refreshToken) is cancelled. If that happens, the refresh token request is not created anymore because the "isRefreshingToken" flag remains in true forever.

**Comment by Devstackr8** [comment]
@mhosman Nice, I am glad it is all working :)

I wasn't aware that if the route is changed that the request would be cancelled.
Are you referring to a route change within the Angular application or a manual route change (by the user refreshing the page / navigating to a new URL via the address bar in the browser)?

If its the latter, then yes the access token won't be updated - but the next time that a web request needs to be made the refresh process will restart. The `isRefreshingToken` boolean won't be set to true in this case because the Angular app has been reloaded therefore the boolean is in its default state (false).

Let me know if my assumption here is wrong, my knowledge on this is rather limited :)

Thanks for the message
Andy

**Comment by mhosman** [comment]
It's an Angular page navigation, not a real one (browser). So if while you are refreshing the token you change the Angular route, the Refresh Token request Will be cancelled and the flag will remain in true. If the new route makes a new request, this request will response a 401 but the refresh token Will not triggered because the flag is in true. I will check if there is some way to detect that cancellation in order to set the flag in false

**Comment by mhosman** [comment]
Ok so... I found the way:

```
switchMap(() => {
         request = this.addHeaders(request);
         return next.handle(request);
}),
finalize(() => {
         this.isRefreshingToken = false;
})
```

But... the problem is that if the request is cancelled, the request will gonna arrive to the server anyway. You will not receive the new token (because the request was cancelled), but if you make the refreshToken request again, you'll get a 401 because the token was refreshed anyway.

The only way to achieve this is to add a loader in order to 'block' the UI while the token is being refreshed.

**Comment by Devstackr8** [comment]
@mhosman I don't understand why the request would be cancelled if the route changes, could you provide a link to docs that outlines this process, or maybe a demo / reproducible example - I would really appreciate it :)

Assuming that the request is cancelled, the `isRefreshingToken` boolean is set to false (as done by your code) and a new request is made which results in a 401 (because of the expired token) then the API won't respond with a 401 - the API has no knowledge of whether you should or shouldn't already have a valid token, so it will just respond with 200 OK and a fresh Access Token (assuming the refresh token is valid).
